# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 44291b69fc59d53988e14badca2259aa8c326b01b831a6815ac2caa390bfe8a5c2e23e59f6ad2d9cbfa324b4ccb0cb4f58e1d1f24d59db6682e1b6e025416ef1

test:
  secret_key_base: fb55f163519e56a0ddffc3557448ac4c1db1e22ed846fcc02e481442631dfc1cede847230b7dfe7d31df7e5c56f41749b48b9bac26ef4901684638ea3a6080ae

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
